### ISSUE TITLE
Make more scriptable (inside Python)

### ISSUE THREAD

**Issue by Cameron-Van-Eck** [AlecThomson/RACS-tools#16]
Hi Alec:

I'm currently thinking about how to set up a convolution step for the VLASS-polarization pipeline, and this seems like it might be the least fuss to implement (the main alternative I'm considering being CASA). I used this tool with great success while prototyping some VLASS results last week.

My biggest complaint at the moment is that it's not immediately clear how easy it would be to integrate this into a Python pipeline (i.e., not using the command line interface). The `smooth()` function looks appropriate, but it's not clear what the inputs are. Would you consider making it more script-friendly (or at a minimum, commenting it a bit more thoroughly so I can see how to use the existing functions)? I'm mostly interested in the 2D version, since the VLASS data is packaged as single planes. In the ideal case (if you're feeling generous), I'm envisioning a function that can I feed an input array, input beam size, target beam size, and method; and get back a convolved array.

Thanks,
Cameron

**Comment by AlecThomson** [comment]
Hi @Cameron-Van-Eck,

Thanks for raising this! I totally agree. Also, we're currently working on a new release, so now seems like a good time for some refactoring.

I'll be pushing some updates soon, so if you feel like testing I'll update this thread

**Comment by AlecThomson** [comment]
I've just pushed a new [branch](https://github.com/AlecThomson/RACS-tools/tree/scripting), which also contains the updates from #15. I would propose we also bring these in for v.2.1.0. This has had the nice benefit of both scripts now sharing the `smooth` function.

@Cameron-Van-Eck feel free to have a look at this branch. I'll also note that you can use `convolve_uv.convolve`, if you want the bare-bones convolution tool.

**Comment by Cameron-Van-Eck** [comment]
Thanks a lot, it's a lot easier to understand now. I'm being pulled in about 20 directions right now, so I'm not sure when I'll get around to integrating this into the VLASS pipeline,but I'll come pester you if I run into any problems. :)

Thanks,
Cameron

**Comment by AlecThomson** [comment]
Leaving this issue open until these updates are merged in ;)
