### ISSUE TITLE
Super-resolution

### ISSUE THREAD

**Issue by AlecThomson** [AlecThomson/RACS-tools#20]
Suggestion from Paddy Leahy - it's possible in some other convolvers to choose a resolution higher than the lowest common resolution. In this case, rather than convolving with a Gaussian, the kernal is an inverse Gaussian - upweighting longer baselines. The tradeoff is that the noise becomes larger. This can be acceptable within some reasonable range.

@wasimraja81 - we should discuss to see if this is possible in our analytic convolution scheme. Care would need to be taken to preserve units in Jy/beam.

**Comment by wasimraja81** [comment]
Hi Alec, 

The analytic method I introduced will convolve the image to any resolution (higher/coarser than the native synthesised beam). 
I do not quite follow the inverse Gaussian method Paddy speaks of. What I do is simple - convolve the un-restored image. 
Once you un-restore, you can restore/convolve with Gaussian of any width. 

wasim
