### ISSUE TITLE
Dattatype of smoothed images are float64

### ISSUE THREAD

**Issue by tjgalvin** [AlecThomson/RACS-tools#36]
It seems like all FITS images produced via the convolution tools appear to be output as an image of a float64 datatype, even if the input image is a single-precision float. It looks like in each of the `convol` modes that the images are cast to `f8`, and are not cast back. 

This is not a huge problem other than more disk than necessary being consumed. 

I think that the fix is a simple one, and have raised #35  to try to address it.

**Comment by AlecThomson** [comment]
Fixed with #35
