### ISSUE TITLE
Target beam and cutoff interplay in beamconv_2D

### ISSUE THREAD

**Issue by tjgalvin** [AlecThomson/RACS-tools#47]
In the larger askap pipeline the beamcon_2D program is called similar to:

```
script_args=" -s conv -v --bmaj 15 --bmin 15 --bpa 0 --cutoff 15.1 --ncores 20"
NCORES=20
log="/scratch/askaprt/askapops/science-processing/53219/logs/convolveCont_AllFields_I_TT0_restored_Full_${SLURM_JOB_ID}.log"
STARTTIME=$(date +%FT%T)
srun --export=ALL --ntasks=1 --cpus-per-task=20 --job-name=findPSF /usr/bin/time -p -o "${log}.timing" beamcon_2D ${script_args} --log ${beamLog} -d ${inputBeamsConvolve[@]} >&"$log"
```
I believe the expected behavior expected by the pipeline is that:
- images below 15'' are convolved to 15'', and
- images above 15.1'' are nan'ed. 

I think the `--cutoff` should really be set of `--cutoff 15`, but ignoring that point for a moment. 

In some recent processing there were a set of images whose beams were larger than the user specified target beam size. Since a target beam has been specified, an explcit check is made against each image to ensure it can be convolved. In the current version this is not considered against the `--cutoff` argument. Specifically, if I am reading things right I think this bit of code should be expanded to only re-raise the BeamError if `cutoff` is None. 

```
for i, (beam, file) in enumerate(
            tqdm(
                zip(allbeams, files),
                total=len(allbeams),
                desc="Deconvolving",
                disable=(logger.level > logging.INFO),
            )
        ):
            try:
                target_beam.deconvolve(beam)
            except ValueError:
                mask_count += 1
                failed.append(file)
            except BeamError as be:
                # BeamError should not be raised if beams are equal
                if target_beam != beam:
                    raise BeamError(be)
``` 

The worker function that performs the actual convolution does the right thing and considers the cutoff value, if specified, as well. If the above `raise BeamError(be)` also considers the value of vutoff, I think this should allow all images above the target beam specified by the user to be nan'ed through setting the cutoff value. 

Any thoughts?

**Comment by AlecThomson** [comment]
Fixed in #49
