### ISSUE TITLE
Move to astropy logging

### ISSUE THREAD

**Issue by dlakaplan** [AlecThomson/RACS-tools#8]
This is an enhancement rather than a fix, but to play better with other code I moved the `print()` commands in `beacon_2D` to use `astropy.log` and set the verbosity level appropriately using the command-line arguments.  The reason I'm mentioning this is because my fork:
https://github.com/dlakaplan/RACS-tools
has those of those fixes alongside the other two issues I raised, and I wanted to be clear what the motivation was.  I personally find it easier this way, but others may have different opinions.

In any case, if you want to merge in this or the other issues I raised (which are more in the ways of fixes) let me know and I'll open a PR.  I can probably try to separate the different issues if I need to.

**Comment by AlecThomson** [comment]
Hey @dlakaplan, thanks for flagging these issues and suggesting these improvements. They all look great! I wasn't familiar with the the astropy logging module before, so thanks for bringing that to my attention. I think we'll need to run some testing before merging this in, but feel free to open a PR anyway for now

**Comment by dlakaplan** [comment]
Thanks, @AlecThomson   I have successfully been using this on our own data (for VAST) but I'm sure a better/more comprehensive test suite would be useful.   If you have anything more formal please let me know.  Otherwise I will submit a PR (or several) and you can test as you did before.

Note that for the logging, I only did it within the `2D` module.  It might make sense to roll that out across the whole package if you want to go that way for the sake of uniformity.

**Comment by dlakaplan** [comment]
Hi, Alec.  I made 5 separate PRs, trying to keep each one distinct.  I think you should be able to deal with them in any order (they don't overlap).  Some are quite small and specific - the logging one is the biggest.

**Comment by AlecThomson** [comment]
Decided that logging was good, but that we would prefer to just the built in logging for now. Unless there's an advantage I'm missing from astropy? Closing for now
